apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "epp-vllm.eppServiceName" . }}-config
  namespace: {{ .Release.Namespace | default .Values.namespace }}
  labels:
    {{- include "epp-vllm.labels" . | nindent 4 }}
    app.kubernetes.io/component: inference-scheduler
data:
  {{- range $filename, $content := .Values.inferenceExtension.pluginsCustomConfig }}
  {{ $filename }}: |
    {{- $content | nindent 4 }}
  {{- end }}
