{{- if and .Values.secret.create .Values.secret.hfTokenValue }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Release.Namespace | default .Values.namespace }}
  labels:
    {{- include "epp-vllm.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.secret.key }}: {{ .Values.secret.hfTokenValue | b64enc }}
{{- end }}
